
DROP DATABASE IF EXISTS webIIC;
CREATE DATABASE webIIC;

use webIIC;

CREATE TABLE image(
	AID			INTEGER(11) 	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PATH		VARCHAR(255)	NOT NULL UNIQUE,
	CLASS		INTEGER(3)		DEFAULT -1
);

